| Agent | Preferred Model | Fallback | Mode | Purpose |
| --- | --- | --- | --- | --- |
| flowforge | __FLOWFORGE_MODEL_flowforge__ | __FLOWFORGE_FALLBACK_flowforge__ | primary | Coordinador CKP-0..4 y orquestador |
| forge-discovery | __FLOWFORGE_MODEL_forge-discovery__ | __FLOWFORGE_FALLBACK_forge-discovery__ | subagent | Context map / CKP-0 |
| forge-arch | __FLOWFORGE_MODEL_forge-arch__ | __FLOWFORGE_FALLBACK_forge-arch__ | subagent | Spec + STRIDE |
| forge-plan | __FLOWFORGE_MODEL_forge-plan__ | __FLOWFORGE_FALLBACK_forge-plan__ | subagent | Planificación |
| forge-dev | __FLOWFORGE_MODEL_forge-dev__ | __FLOWFORGE_FALLBACK_forge-dev__ | subagent | Implementación y tests |
| forge-verify | __FLOWFORGE_MODEL_forge-verify__ | __FLOWFORGE_FALLBACK_forge-verify__ | subagent | Auditoría (verify-report) |
| forge-memory | __FLOWFORGE_MODEL_forge-memory__ | __FLOWFORGE_FALLBACK_forge-memory__ | subagent | Cierre y memoria |
| forge-teacher | __FLOWFORGE_MODEL_forge-teacher__ | __FLOWFORGE_FALLBACK_forge-teacher__ | subagent | Explicaciones (teacher mode) |
| default | __FLOWFORGE_MODEL_default__ | __FLOWFORGE_FALLBACK_default__ | primary | Modelo por defecto cuando no se detecta agente |

<!-- Generated by FlowForge installer from opencode.json provider block. Do NOT edit directly. -->
