using System.Text;

namespace FlowForge.Installer.Onboarding;

/// <summary>
/// Generates ONBOARDING.md from OnboardingData (FR-006).
/// Default location is project root; NEVER writes to .ai-work/ (ADR-004).
/// </summary>
public static class MarkdownExporter
{
    /// <summary>
    /// Write ONBOARDING.md to specified path (or project root if null).
    /// NEVER writes to .ai-work/ directory.
    /// </summary>
    public static string Export(OnboardingData data, string? outputPath = null)
    {
        var resolvedPath = ResolveOutputPath(outputPath);
        var content = GenerateMarkdown(data);
        File.WriteAllText(resolvedPath, content, Encoding.UTF8);
        return resolvedPath;
    }

    /// <summary>
    /// Generate the markdown content without writing to disk (for testability).
    /// </summary>
    public static string GenerateMarkdown(OnboardingData data)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine($"# Onboarding: {data.Project}");
        sb.AppendLine();
        sb.AppendLine($"**Generated**: {data.GeneratedAt:yyyy-MM-dd HH:mm}");
        sb.AppendLine($"**User**: {data.User}");
        sb.AppendLine();

        // Recent Activity
        sb.AppendLine("## Recent Activity");
        sb.AppendLine();
        if (data.RecentSessions.Count == 0)
        {
            sb.AppendLine("_No recent sessions found._");
        }
        else
        {
            foreach (var session in data.RecentSessions)
            {
                sb.AppendLine($"- **{session.Title}** ({session.Timestamp:yyyy-MM-dd})");
                if (!string.IsNullOrWhiteSpace(session.Content))
                {
                    // Indent content as a block quote
                    foreach (var line in session.Content.Split('\n'))
                    {
                        var trimmed = line.TrimEnd('\r');
                        if (!string.IsNullOrWhiteSpace(trimmed))
                            sb.AppendLine($"  > {trimmed}");
                    }
                }
                sb.AppendLine();
            }
        }

        // Key Decisions
        sb.AppendLine("## Key Decisions");
        sb.AppendLine();
        if (data.Decisions.Count == 0)
        {
            sb.AppendLine("_No decisions recorded._");
        }
        else
        {
            foreach (var decision in data.Decisions)
            {
                sb.AppendLine($"### {decision.Title}");
                sb.AppendLine();
                sb.AppendLine($"_{decision.Timestamp:yyyy-MM-dd}_");
                sb.AppendLine();
                if (!string.IsNullOrWhiteSpace(decision.Content))
                {
                    sb.AppendLine(decision.Content);
                }
                sb.AppendLine();
            }
        }

        // Reusable Patterns
        sb.AppendLine("## Reusable Patterns");
        sb.AppendLine();
        if (data.Patterns.Count == 0)
        {
            sb.AppendLine("_No patterns recorded._");
        }
        else
        {
            foreach (var pattern in data.Patterns)
            {
                sb.AppendLine($"### {pattern.Title}");
                sb.AppendLine();
                sb.AppendLine($"_{pattern.Timestamp:yyyy-MM-dd}_");
                sb.AppendLine();
                if (!string.IsNullOrWhiteSpace(pattern.Content))
                {
                    sb.AppendLine(pattern.Content);
                }
                sb.AppendLine();
            }
        }

        // Footer
        sb.AppendLine("---");
        sb.AppendLine("*Generated by `flowforge onboard`*");

        return sb.ToString();
    }

    /// <summary>
    /// Resolve the output path. Default is project root / ONBOARDING.md.
    /// Validates that the path is NOT inside .ai-work/ (ADR-004).
    /// </summary>
    public static string ResolveOutputPath(string? outputPath)
    {
        string resolved;

        if (string.IsNullOrWhiteSpace(outputPath))
        {
            // Default: project root
            resolved = Path.Combine(Directory.GetCurrentDirectory(), "ONBOARDING.md");
        }
        else if (Path.IsPathRooted(outputPath))
        {
            resolved = outputPath;
        }
        else
        {
            resolved = Path.Combine(Directory.GetCurrentDirectory(), outputPath);
        }

        // Safety check: never write to .ai-work/
        var normalized = Path.GetFullPath(resolved);
        if (normalized.Contains(Path.DirectorySeparatorChar + ".ai-work" + Path.DirectorySeparatorChar) ||
            normalized.Contains(Path.AltDirectorySeparatorChar + ".ai-work" + Path.AltDirectorySeparatorChar) ||
            normalized.EndsWith(Path.DirectorySeparatorChar + ".ai-work") ||
            normalized.EndsWith(Path.AltDirectorySeparatorChar + ".ai-work"))
        {
            throw new InvalidOperationException(
                "ONBOARDING.md must not be written to .ai-work/ directory (ADR-004). " +
                "Use --output to specify a different path.");
        }

        return resolved;
    }
}
