using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using FlowForge.Installer.Modules.OpenCode;

namespace FlowForge.Installer.Modules.OpenCode;

public sealed class ModelAssignmentsGenerator
{
    static readonly string[] AgentOrder =
    {
        "flowforge",
        "forge-discovery",
        "forge-arch",
        "forge-plan",
        "forge-dev",
        "forge-verify",
        "forge-memory",
        "forge-teacher",
        "default"
    };

    readonly string _manifestPath;
    readonly string _outputPath;
    readonly string _provider;

    public ModelAssignmentsGenerator(string manifestPath, string outputPath, string provider)
    {
        _manifestPath = manifestPath;
        _outputPath = outputPath;
        _provider = string.IsNullOrWhiteSpace(provider) ? "opencode-zen" : provider;
    }

    public void Generate(string opencodeJsonPath)
    {
        var manifest = JsonSerializer.Deserialize(
            File.ReadAllText(_manifestPath),
            OpenCodeJsonContext.Default.AgentModelsManifest)
                       ?? throw new InvalidOperationException("No agent models manifest");

        var builder = new StringBuilder();
        builder.AppendLine("| Agent | Preferred Model | Fallback | Mode | Purpose |");
        builder.AppendLine("| --- | --- | --- | --- | --- |");

        foreach (var agent in AgentOrder)
        {
            if (!manifest.Agents.TryGetValue(agent, out var entry))
                continue;

            var preferred = manifest.ResolveAgentModel(agent, _provider);
            var fallback = manifest.ResolveAgentFallback(agent, _provider);
            builder.AppendLine($"| {agent} | `{preferred}` | `{fallback}` | {entry.Mode} | {entry.Purpose} |");
        }

        builder.AppendLine();
        builder.AppendLine("<!-- Generated by FlowForge installer from opencode.json provider block. Do NOT edit directly. -->");

        Directory.CreateDirectory(Path.GetDirectoryName(_outputPath) ?? string.Empty);
        File.WriteAllText(_outputPath, builder.ToString());
    }
}
