using System.Linq;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace FlowForge.Installer.Modules.OpenCode;

public sealed class ModelAssignmentsGenerator
{
    static readonly string[] AgentOrder =
    {
        "flowforge",
        "forge-discovery",
        "forge-arch",
        "forge-plan",
        "forge-dev",
        "forge-verify",
        "forge-memory",
        "forge-teacher",
        "default"
    };

    readonly string _manifestPath;
    readonly string _outputPath;

    public ModelAssignmentsGenerator(string manifestPath, string outputPath)
    {
        _manifestPath = manifestPath;
        _outputPath = outputPath;
    }

    public void Generate(string opencodeJsonPath)
    {
        var providerModels = ReadProviderModels(opencodeJsonPath);
        var manifest = JsonSerializer.Deserialize<AgentManifest>(File.ReadAllText(_manifestPath))
                       ?? throw new InvalidOperationException("No agent models manifest");

        var builder = new StringBuilder();
        builder.AppendLine("| Agent | Preferred Model | Fallback | Mode | Purpose |");
        builder.AppendLine("| --- | --- | --- | --- | --- |");

        foreach (var agent in AgentOrder)
        {
            if (!manifest.Agents.TryGetValue(agent, out var entry))
                continue;

            var preferred = ToPrefixed(entry.Model, providerModels);
            var fallback = ToPrefixed(entry.Fallback, providerModels);
            builder.AppendLine($"| {agent} | {preferred} | {fallback} | {entry.Mode} | {entry.Purpose} |");
        }

        builder.AppendLine();
        builder.AppendLine("<!-- Generated by FlowForge installer from opencode.json provider block. Do NOT edit directly. -->");

        Directory.CreateDirectory(System.IO.Path.GetDirectoryName(_outputPath) ?? string.Empty);
        File.WriteAllText(_outputPath, builder.ToString());
    }

    static string[] ReadProviderModels(string opencodeJsonPath)
    {
        var text = File.ReadAllText(opencodeJsonPath);
        using var doc = JsonDocument.Parse(text);
        if (!doc.RootElement.TryGetProperty("provider", out var provider))
            return Array.Empty<string>();

        if (!provider.TryGetProperty("opencode-zen", out var zen))
            return Array.Empty<string>();

        if (!zen.TryGetProperty("models", out var models))
            return Array.Empty<string>();

        return models.EnumerateArray()
                     .Select(e => e.GetString())
                     .Where(m => !string.IsNullOrWhiteSpace(m))
                     .ToArray()!;
    }

    static string ToPrefixed(string model, string[] providerModels)
    {
        var clean = model.Replace("__FLOWFORGE_MODEL__", "big-pickle");
        if (Array.IndexOf(providerModels, clean) == -1)
            clean = "big-pickle";
        return $"opencode-zen/{clean.Split('/', StringSplitOptions.RemoveEmptyEntries).Last()}";
    }

    sealed record AgentManifest([property: JsonPropertyName("agents")] Dictionary<string, AgentEntry> Agents);

    sealed record AgentEntry(
        [property: JsonPropertyName("model")] string Model,
        [property: JsonPropertyName("fallback")] string Fallback,
        [property: JsonPropertyName("mode")] string Mode,
        [property: JsonPropertyName("purpose")] string Purpose);
}
