using FlowForge.Installer.Onboarding;
using Xunit;

namespace FlowForge.Installer.Tests.Onboarding;

/// <summary>
/// Unit tests for MarkdownExporter (FR-006).
/// </summary>
public class MarkdownExporterTests
{
    [Fact]
    public void FR_006_GenerateMarkdown_ContainsAllSections()
    {
        // Given complete onboarding data
        var data = CreateSampleData();

        // When generating markdown
        var md = MarkdownExporter.GenerateMarkdown(data);

        // Then all sections are present
        Assert.Contains("# Onboarding: test-project", md);
        Assert.Contains("## Recent Activity", md);
        Assert.Contains("## Key Decisions", md);
        Assert.Contains("## Reusable Patterns", md);
        Assert.Contains("*Generated by `flowforge onboard`*", md);
    }

    [Fact]
    public void FR_006_GenerateMarkdown_ContainsSessionData()
    {
        var data = CreateSampleData();
        var md = MarkdownExporter.GenerateMarkdown(data);

        Assert.Contains("Session One", md);
        Assert.Contains("Session Two", md);
    }

    [Fact]
    public void FR_006_GenerateMarkdown_ContainsDecisionData()
    {
        var data = CreateSampleData();
        var md = MarkdownExporter.GenerateMarkdown(data);

        Assert.Contains("Decision A", md);
        Assert.Contains("Decision B", md);
    }

    [Fact]
    public void FR_006_GenerateMarkdown_ContainsPatternData()
    {
        var data = CreateSampleData();
        var md = MarkdownExporter.GenerateMarkdown(data);

        Assert.Contains("Pattern X", md);
    }

    [Fact]
    public void FR_006_GenerateMarkdown_EmptySessions_ShowsNotice()
    {
        var data = new OnboardingData(
            "proj", "user", DateTime.Now,
            RecentSessions: [],
            Decisions: [new Observation("1", "D1", "decision", "content", DateTime.Now)],
            Patterns: []
        );

        var md = MarkdownExporter.GenerateMarkdown(data);

        Assert.Contains("_No recent sessions found._", md);
    }

    [Fact]
    public void FR_006_GenerateMarkdown_EmptyDecisions_ShowsNotice()
    {
        var data = new OnboardingData(
            "proj", "user", DateTime.Now,
            RecentSessions: [],
            Decisions: [],
            Patterns: []
        );

        var md = MarkdownExporter.GenerateMarkdown(data);

        Assert.Contains("_No decisions recorded._", md);
    }

    [Fact]
    public void FR_006_GenerateMarkdown_EmptyPatterns_ShowsNotice()
    {
        var data = new OnboardingData(
            "proj", "user", DateTime.Now,
            RecentSessions: [],
            Decisions: [],
            Patterns: []
        );

        var md = MarkdownExporter.GenerateMarkdown(data);

        Assert.Contains("_No patterns recorded._", md);
    }

    [Fact]
    public void FR_006_GenerateMarkdown_ContainsUserAndTimestamp()
    {
        var generatedAt = new DateTime(2024, 6, 15, 10, 30, 0);
        var data = new OnboardingData(
            "my-project", "test@example.com", generatedAt,
            RecentSessions: [], Decisions: [], Patterns: []
        );

        var md = MarkdownExporter.GenerateMarkdown(data);

        Assert.Contains("**User**: test@example.com", md);
        Assert.Contains("2024-06-15", md);
    }

    [Fact]
    public void FR_006_ResolveOutputPath_DefaultIsProjectRoot()
    {
        var path = MarkdownExporter.ResolveOutputPath(null);
        Assert.EndsWith("ONBOARDING.md", path);
        Assert.DoesNotContain(".ai-work", path);
    }

    [Fact]
    public void FR_006_ResolveOutputPath_ExplicitPath()
    {
        var path = MarkdownExporter.ResolveOutputPath("/tmp/test-onboarding.md");
        Assert.Equal("/tmp/test-onboarding.md", path);
    }

    [Fact]
    public void FR_006_ResolveOutputPath_NeverAiWork()
    {
        // ADR-004: ONBOARDING.md must NEVER be written to .ai-work/
        Assert.Throws<InvalidOperationException>(() =>
            MarkdownExporter.ResolveOutputPath(".ai-work/test/ONBOARDING.md"));
    }

    [Fact]
    public void FR_006_Export_WritesFile()
    {
        var data = CreateSampleData();
        var tempFile = Path.Combine(Path.GetTempPath(), $"onboarding-test-{Guid.NewGuid()}.md");

        try
        {
            var resultPath = MarkdownExporter.Export(data, tempFile);
            Assert.Equal(tempFile, resultPath);
            Assert.True(File.Exists(tempFile));

            var content = File.ReadAllText(tempFile);
            Assert.Contains("# Onboarding: test-project", content);
        }
        finally
        {
            if (File.Exists(tempFile))
                File.Delete(tempFile);
        }
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static OnboardingData CreateSampleData()
    {
        return new OnboardingData(
            Project: "test-project",
            User: "test-user",
            GeneratedAt: new DateTime(2024, 1, 15, 10, 0, 0),
            RecentSessions:
            [
                new Session("Session One", "First session content", new DateTime(2024, 1, 15)),
                new Session("Session Two", "Second session content", new DateTime(2024, 1, 14)),
            ],
            Decisions:
            [
                new Observation("1", "Decision A", "decision", "What: Did A\nWhy: Because", new DateTime(2024, 1, 15)),
                new Observation("2", "Decision B", "decision", "What: Did B\nWhy: Because", new DateTime(2024, 1, 14)),
            ],
            Patterns:
            [
                new Observation("1", "Pattern X", "pattern", "What: Pattern X\nWhy: Reusable", new DateTime(2024, 1, 15)),
            ]
        );
    }
}
