#!/usr/bin/env bash
set -euo pipefail

command -v jq >/dev/null 2>&1 || { echo "jq no disponible" >&2; exit 1; }
command -v envsubst >/dev/null 2>&1 || { echo "envsubst no disponible" >&2; exit 1; }

FF_REPO="${1:?Usage: generate-config.sh <FLOWFORGE_REPO>}"
FF_REPO="${FF_REPO//\\//}"
TEMPLATES="$FF_REPO/ide/opencode/templates"
CONFIG_DIR="$FF_REPO/ide/opencode/config"
LIB_DIR="$FF_REPO/ide/opencode/lib"

OC_DIR="$HOME/.config/opencode"
CONFIG="$OC_DIR/opencode.json"
SIDECAR="$OC_DIR/.flowforge-managed.json"
RULES="$OC_DIR/.agents/rules/model-assignments.md"
BACKUP_DIR="$HOME/.flowforge-backups/$(date -u +%Y%m%d-%H%M%S)"

for lib in "$LIB_DIR"/*.sh; do
  [ -f "$lib" ] && source "$lib"
done

mkdir -p "$OC_DIR" "$BACKUP_DIR" "$(dirname "$RULES")"
if [ -f "$CONFIG" ]; then
  cp "$CONFIG" "$BACKUP_DIR/"
fi

HOME="${HOME}"
USER="${USER:-$(whoami)}"
export FLOWFORGE_REPO="$FF_REPO" HOME USER FLOWFORGE_ENGRAM_BIN="$HOME/.local/bin/engram"

json="$(envsubst < "$TEMPLATES/opencode.json.tpl")"
AGENTS="forge-orchestrator forge-discovery forge-arch forge-plan forge-dev forge-verify forge-memory forge-teacher"
for agent in $AGENTS; do
  model="$(jq -r ".agents[\"$agent\"].model" "$CONFIG_DIR/agent-models.json")"
  json="$(printf '%s' "$json" | jq --arg agent "$agent" --arg model "opencode-zen/$model" '.agent[$agent].model = $model')"
done

if [ -f "$CONFIG" ]; then
  existing="$(jq -c '.' "$CONFIG")"
else
  existing="{}"
fi

managed_paths_file="$SIDECAR"
if [ ! -f "$SIDECAR" ]; then
  managed_paths_file="$TEMPLATES/managed-paths.json"
fi

merged="$(jq -n \
  --argjson existing "$existing" \
  --argjson new "$json" \
  --arg agents "$AGENTS" \
  '
  ($existing // {}) as $base
  | reduce ($agents | split(" "))[] as $agent (
      $base;
      .agent[$agent] = $new.agent[$agent]
  )
  | .instructions = $new.instructions
  | .permission = $new.permission
  | .mcp = (.mcp // {}) | .mcp["engram"] = $new.mcp["engram"]
  | .provider = (.provider // {}) | .provider["opencode-zen"] = $new.provider["opencode-zen"]
'
)"

pii_scan_string "$merged" "opencode.json"
atomic_write "$CONFIG" "$merged" 0
atomic_write "$SIDECAR" "$(cat "$managed_paths_file")" 0

tmp_rules="$(mktemp "$RULES.XXXXXX")"
cat <<'EOF' > "$tmp_rules"
| Agent | Preferred Model | Fallback | Mode | Purpose |
| --- | --- | --- | --- | --- |
EOF

for agent in $AGENTS default; do
  model="$(jq -r ".agents[\"$agent\"].model" "$CONFIG_DIR/agent-models.json")"
  fallback="$(jq -r ".agents[\"$agent\"].fallback" "$CONFIG_DIR/agent-models.json")"
  mode="$(jq -r ".agents[\"$agent\"].mode" "$CONFIG_DIR/agent-models.json")"
  purpose="$(jq -r ".agents[\"$agent\"].purpose" "$CONFIG_DIR/agent-models.json")"
  echo "| $agent | opencode-zen/$model | opencode-zen/$fallback | $mode | $purpose |" >> "$tmp_rules"
done

cat <<'EOF' >> "$tmp_rules"

<!-- Generated by FlowForge installer bash from opencode.json provider block -->
EOF

atomic_write "$RULES" "$(cat "$tmp_rules")" 0
rm -f "$tmp_rules"

install_log_append "$BACKUP_DIR" "bash generate-config.sh completed"

echo "⚠ Free Zen models may use your prompts/data for training. Do NOT send proprietary or sensitive code."
