#!/usr/bin/env bash
set -euo pipefail

command -v jq >/dev/null 2>&1 || { echo "jq no disponible" >&2; exit 1; }
command -v envsubst >/dev/null 2>&1 || { echo "envsubst no disponible" >&2; exit 1; }

FF_REPO="${1:?Usage: generate-config.sh <FLOWFORGE_REPO>}"
FF_REPO="${FF_REPO//\\//}"
TEMPLATES="$FF_REPO/ide/opencode/templates"
LIB_DIR="$FF_REPO/ide/opencode/lib"

OC_DIR="$HOME/.config/opencode"
CONFIG="$OC_DIR/opencode.json"
SIDECAR="$OC_DIR/.flowforge-managed.json"
RULES="$OC_DIR/.agents/rules/model-assignments.md"
BACKUP_DIR="$HOME/.flowforge-backups/$(date -u +%Y%m%d-%H%M%S)"

for lib in "$LIB_DIR"/*.sh; do
  [ -f "$lib" ] && source "$lib"
done

mkdir -p "$OC_DIR" "$BACKUP_DIR" "$(dirname "$RULES")"
if [ -f "$CONFIG" ]; then
  cp "$CONFIG" "$BACKUP_DIR/"
fi

HOME="${HOME}"
USER="${USER:-$(whoami)}"
export FLOWFORGE_REPO="$FF_REPO" HOME USER FLOWFORGE_ENGRAM_BIN="$HOME/.local/bin/engram"

json="$(envsubst '$FLOWFORGE_REPO $FLOWFORGE_ENGRAM_BIN $USER' < "$TEMPLATES/opencode.json.tpl")"
AGENTS="flowforge forge-discovery forge-arch forge-plan forge-dev forge-verify forge-memory forge-teacher"
provider="${FLOWFORGE_PROVIDER:-opencode-zen}"
if ! printf '%s' "$json" | jq -e --arg provider "$provider" '.provider[$provider]' >/dev/null 2>&1; then
  provider="$(printf '%s' "$json" | jq -r '.provider | keys[] | select(. == "opencode-zen") // empty' 2>/dev/null || true)"
  provider="${provider:-$(printf '%s' "$json" | jq -r '.provider | keys[0] // \"opencode-zen\"')}"
fi
SCHEMA_KEY='$schema'

resolve_agent_field() {
  local agent_name="$1"
  local field_name="$2"
  jq -r --arg agent "$agent_name" --arg provider "$provider" --arg field "$field_name" '
    (.agents[$agent][$field][$provider]) // (.agents[$agent][$field])
  ' "$TEMPLATES/agent-models.json"
}

format_model_reference() {
  local raw="$1"
  if [[ "$raw" == */* ]]; then
    printf '%s' "$raw"
  else
    printf '%s/%s' "$provider" "$raw"
  fi
}

for agent in $AGENTS; do
  raw_model="$(resolve_agent_field "$agent" "model")"
  if [ -z "$raw_model" ] || [ "$raw_model" = "null" ]; then
    echo "Modelo no configurado para $agent @ $provider" >&2
    exit 1
  fi
  full_model="$(format_model_reference "$raw_model")"
  json="$(printf '%s' "$json" | jq --arg agent "$agent" --arg model "$full_model" '.agent[$agent].model = $model')"
done

if ! printf '%s' "$json" | jq -e '.provider["opencode-zen"].models | type == "object"' >/dev/null 2>&1; then
  echo "provider.opencode-zen.models must be an object" >&2
  exit 1
fi

if ! printf '%s' "$json" | jq -e '(.permission.bash | type == "object") and (.permission.read | type == "object")' >/dev/null 2>&1; then
  echo "permission.bash and permission.read must be objects" >&2
  exit 1
fi

if ! printf '%s' "$json" | jq -e '.agent | to_entries | map(.value.tools) | map(type == "object") | all' >/dev/null 2>&1; then
  echo "agent.*.tools must all be objects" >&2
  exit 1
fi

if [ -f "$CONFIG" ]; then
  existing="$(jq -c '.' "$CONFIG")"
else
  existing="{}"
fi

managed_paths_file="$SIDECAR"
if [ ! -f "$SIDECAR" ]; then
  managed_paths_file="$TEMPLATES/managed-paths.json"
fi

merged="$(jq -n \
  --argjson existing "$existing" \
  --argjson new "$json" \
  --arg agents "$AGENTS" \
  --arg schema_key "$SCHEMA_KEY" \
  '
  ($existing // {}) as $base
  | reduce ($agents | split(" "))[] as $agent (
      $base;
      .agent[$agent] = $new.agent[$agent]
  )
  | .instructions = $new.instructions
  | .permission = $new.permission
  | .mcp = (.mcp // {}) | .mcp["engram"] = $new.mcp["engram"]
  | .provider = ((.provider // {}) + ($new.provider // {}))
  | .[$schema_key] = $new[$schema_key]
'
)"

pii_scan_string "$merged" "opencode.json"
atomic_write "$CONFIG" "$merged" 0
atomic_write "$SIDECAR" "$(cat "$managed_paths_file")" 0

tmp_rules="$(mktemp "$RULES.XXXXXX")"
cat <<'EOF' > "$tmp_rules"
| Agent | Preferred Model | Fallback | Mode | Purpose |
| --- | --- | --- | --- | --- |
EOF

for agent in $AGENTS default; do
  raw_model="$(resolve_agent_field "$agent" "model")"
  raw_fallback="$(resolve_agent_field "$agent" "fallback")"
  if [ -z "$raw_model" ] || [ "$raw_model" = "null" ]; then
    echo "Modelo no configurado para $agent @ $provider (rules table)" >&2
    exit 1
  fi
  if [ -z "$raw_fallback" ] || [ "$raw_fallback" = "null" ]; then
    echo "Fallback no configurado para $agent @ $provider (rules table)" >&2
    exit 1
  fi
  preferred_model="$(format_model_reference "$raw_model")"
  fallback_model="$(format_model_reference "$raw_fallback")"
  mode="$(jq -r ".agents[\"$agent\"].mode" "$TEMPLATES/agent-models.json")"
  purpose="$(jq -r ".agents[\"$agent\"].purpose" "$TEMPLATES/agent-models.json")"
  echo "| $agent | $preferred_model | $fallback_model | $mode | $purpose |" >> "$tmp_rules"
done

cat <<'EOF' >> "$tmp_rules"

<!-- Generated by FlowForge installer bash from opencode.json provider block -->
EOF

atomic_write "$RULES" "$(cat "$tmp_rules")" 0
rm -f "$tmp_rules"

install_log_append "$BACKUP_DIR" "bash generate-config.sh completed"

echo "⚠ Free Zen models may use your prompts/data for training. Do NOT send proprietary or sensitive code."
